export const INCOME_CATEGORIES = [
  "Salary",
  "Freelance",
  "Business",
  "Bonus",
  "Interest",
  "Rental",
  "Dividends",
  "Investments",
  "Side Hustle",
  "Commissions",
  "Grants & Scholarships",
  "Gifts & Allowances",
  "Refunds & Cashbacks",
  "Crypto Gains",
  "Other"
];

export const EXPENSE_CATEGORIES = [
  "Food",
  "Groceries",
  "Shopping",
  "Transportation",
  "Rent",
  "Bills",
  "Entertainment",
  "Education",
  "Healthcare",
  "Travel",
  "EMI",
  "Subscription",
  "Fitness & Sports",
  "Personal Care",
  "Home Maintenance",
  "Insurance",
  "Taxes",
  "Gifts & Donations",
  "Pet Care",
  "Other"
];

export const INVESTMENT_TYPES = [
  "Stocks",
  "Mutual Funds",
  "SIP",
  "Fixed Deposit",
  "Gold",
  "Cryptocurrency",
  "Bonds",
  "Real Estate",
  "PPF",
  "NPS",
  "Other"
];

export const PAYMENT_METHODS = [
  "Bank Transfer",
  "Credit Card",
  "Debit Card",
  "UPI / QR",
  "Cash",
  "Net Banking",
  "Cheque",
  "Portfolio / Demat",
  "Other"
];

export const CATEGORY_COLORS = {
  Food: "#F97316",
  Groceries: "#84CC16",
  Shopping: "#EC4899",
  Transportation: "#8B5CF6",
  Rent: "#3B82F6",
  Bills: "#EAB308",
  Entertainment: "#06B6D4",
  Education: "#10B981",
  Healthcare: "#EF4444",
  Travel: "#6366F1",
  EMI: "#F43F5E",
  Subscription: "#14B8A6",
  "Fitness & Sports": "#10B981",
  "Personal Care": "#F472B6",
  "Home Maintenance": "#A855F7",
  Insurance: "#0EA5E9",
  Taxes: "#64748B",
  "Gifts & Donations": "#F43F5E",
  "Pet Care": "#F59E0B",
  Other: "#64748B",
  Salary: "#10B981",
  Freelance: "#3B82F6",
  Business: "#8B5CF6",
  Bonus: "#F59E0B",
  Interest: "#06B6D4",
  Rental: "#EC4899",
  Dividends: "#10B981",
  Investments: "#6366F1",
  "Side Hustle": "#8B5CF6",
  Commissions: "#F59E0B",
  "Grants & Scholarships": "#0EA5E9",
  "Gifts & Allowances": "#F472B6",
  "Refunds & Cashbacks": "#84CC16",
  "Crypto Gains": "#F97316",
  Stocks: "#3B82F6",
  "Mutual Funds": "#10B981",
  SIP: "#8B5CF6",
  "Fixed Deposit": "#F59E0B",
  Gold: "#EAB308",
  Cryptocurrency: "#F97316",
  Bonds: "#06B6D4",
  "Real Estate": "#6366F1",
  PPF: "#14B8A6",
  NPS: "#EC4899"
};

